# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "auto_migrations"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["sai (originally by PJ Hyett)"]
  s.date = "2021-12-05"
  s.description = "Auto database migration."
  s.email = "rubyer1993@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "auto_migrations.gemspec",
    "init.rb",
    "lib/auto_migrations.rb",
    "lib/tasks/auto_migrations_tasks.rake",
    "test/auto_migration_test.rb"
  ]
  s.homepage = "https://github.com/sai1024/auto_migrations"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.6"
  s.summary = "Auto database migration."
end

