# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: db_auto_migrations 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "db_auto_migrations".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["sai (originally by PJ Hyett)".freeze]
  s.date = "2021-12-07"
  s.description = "Auto database migration.".freeze
  s.email = "rubyer1993@gmail.com".freeze
  s.executables = ["setup".freeze]
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "bin/setup",
    "db_auto_migrations.gemspec",
    "init.rb",
    "lib/db_auto_migrations.rb",
    "lib/tasks/db_auto_migrations_tasks.rake",
    "test/db_auto_migrations_test.rb"
  ]
  s.homepage = "https://github.com/sai1024/auto_migrations".freeze
  s.rubygems_version = "3.0.9".freeze
  s.summary = "Auto database migration.".freeze
end

